### PR TITLE
Add golist for podman

### PR DESCRIPTION
**Pull request by lachmanfrantisek**
Requested by @lsm5 because of
https://github.com/containers/podman/issues/19094

### CODE REVIEW

**Review by jpopelka — APPROVED** [review]

**Comment by lsm5** [comment]
@lachmanfrantisek Thanks a lot for including this. Just curious if it's deployed already because another propose-downstream also failed similarly just now. https://github.com/containers/buildah/issues/4904

**Comment by jpopelka** [comment]
Hm, that's strange, yes it's already there
```
$ podman run -ti --rm quay.io/packit/sandcastle:prod rpm -qv golist
  golist-0.10.1-11.fc37.x86_64
```

**Comment by jpopelka** [comment]
I can see ["imagePullPolicy": "IfNotPresent"](https://github.com/packit/sandcastle/blob/dd34db4039fe5e0ffd758eda079f1fb9db06792d/sandcastle/api.py#L173) in the `Sandcastle.set_pod_manifest()`.
@TomasTomecek how can I make sandcastle to pull a newer image?

**Comment by lsm5** [comment]
@jpopelka @lachmanfrantisek I'll handle this dep in podman/ buildah itself. https://github.com/containers/podman/pull/19117 Please feel free to revert this change. Sorry about the PITA.

**Comment by lachmanfrantisek** [comment]
@lsm5 OK, thanks for the fix/workaround on your side!

**Pull request merged**
