### PR TITLE
Install rust2rpm

### PR DESCRIPTION
**Pull request by nforro**

### CODE REVIEW

**Review by mfocko — APPROVED** [review]

**Comment by nforro** [comment]
Ops, it won't be so easy, rust2rpm is not in EPEL9 :frowning_face:

**Review by mfocko — APPROVED** [review]

**Review by lbarcziova — APPROVED** [review]

**Comment by nforro** [comment]
No, this won't fly either, the installation works but rust2rpm command fails immediately because of cargo2rpm that doesn't support Python 3.9. Fortunately cargo2rpm is packaged for EPEL 9, so installing it with dnf should fix it :sweat_smile:

**Comment by nforro** [comment]
Nope, it is packaged, but it doesn't work, it uses Python 3.10 syntax so it immediately fails on import :roll_eyes:

**Comment by nforro** [comment]
Ok, it looks like this is working, let me merge it.

**Pull request merged**
